### PR TITLE
fix: do not sanitize file names

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

Do not sanitize file names. At the moment inside generator, we have feature called `File templates` and we cannot sanitize `$` chars, which is introduced in the newest version of rollup.

**Related issue(s)**
See PR https://github.com/asyncapi/dotnet-nats-template

### CODE REVIEW

**Comment by magicmatatjahu** [comment]
@jonaslagoni Added :) Thanks!

**Comment by jonaslagoni** [comment]
I guess windows don't like that particular filename 😅

**Comment by magicmatatjahu** [comment]
@jonaslagoni Yeah, I see 😅  I changed to the `$$simple$$` to check only our file templates :)

**Comment by magicmatatjahu** [comment]
@jonaslagoni Ok, it works :)

**Review by jonaslagoni — APPROVED** [review]
LGTM 👍

**Pull request merged**
