### PR TITLE
feat: integrate context feature

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

Integrate context feature inside React renderer:
- create `createContext` and `useContent` functions (similar logic like in normal React),
- update `createElement` function to handle context,
- write unit tests.

NOTE: This feature at the moment doesn't work in asynchronous code, because context like in React operates on global currentContext/currentDispatcher. I'll think how to handle parallel case.

**Related issue(s)**
Resolves https://github.com/asyncapi/generator-react-sdk/issues/18
See also https://github.com/asyncapi/shape-up-process/issues/54

### CODE REVIEW

**Comment by fmvilas** [comment]
What is `context` needed for in our case?

**Comment by magicmatatjahu** [comment]
@fmvilas Use case is described in linked issue. If we decide to go with React as renderer-client for our model generation it will help us to avoid props hell. This PR is only a quick draft to show how it could be done, I mean integration in code. If we decide to go with plain string templates, probably I will close PR.

**Comment by fmvilas** [comment]
Oh sorry, I missed that. Thanks!

**Comment by jonaslagoni** [comment]
@magicmatatjahu same here, any reason it fell through the cracks?

**Pull request closed without merging**
