### PR TITLE
feat!: update parser types

### LINKED ISSUE #161: Release as version 1
#### Reason/Context
Since its creation we have used version 0, however with more than 1 year with no bugs, I think it's fair to say we can release this as being stable version 1 🙂

@magicmatatjahu what do you think?

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**
This PR updates parser types and version.

Blocked by https://github.com/asyncapi/generator-react-sdk/pull/181
Fixes #161 
Blocking https://github.com/asyncapi/markdown-template/pull/360

### CODE REVIEW

**Review by magicmatatjahu — APPROVED** [review]

**Comment by jonaslagoni** [comment]
@magicmatatjahu wanna do major version for this so we fix #161?

**Review by magicmatatjahu — APPROVED** [review]

**Comment by magicmatatjahu** [comment]
@jonaslagoni You can.

**Comment by jonaslagoni** [comment]
Thanks for the quick review @magicmatatjahu 🙏

**Pull request merged**
