### PR TITLE
chore: remove html docs

### PR DESCRIPTION
**Pull request by jonaslagoni**
As discussed in #1 docs should be added afterwards to reduce complexity of the PR.

### CODE REVIEW

**Comment by derberg** [comment]
if it is a full blown html, wouldn't it be better to push it to gh pages? that would make it much better to read and acces

**Comment by jonaslagoni** [comment]
> @jonaslagoni if it is a full blown html, wouldn't it be better to push it to gh pages? that would make it much better to read and acces

hmm maybe? I thought these html pages could be integrated into our website somehow :)

**Comment by derberg** [comment]
@jonaslagoni long term sure, but I see it is static HTML, not so easy to embed, probably has some unique style, so first time integration would be "just paste a link to gh page 😄 "

the thing is that I'm not sure when this work will get into the scope, so better to have good solution in between, and setting up GH Pages with GH Actions is easy

**Comment by jonaslagoni** [comment]
> @jonaslagoni long term sure, but I see it is static HTML, not so easy to embed, probably has some unique style, so first time integration would be "just paste a link to gh page 😄 "
> 
> the thing is that I'm not sure when this work will get into the scope, so better to have good solution in between, and setting up GH Pages with GH Actions is easy

Sounds like you know just what to do xD? Havent really used GitHub Pages :D question is if the markdown isent enough for now then until it gets introduced or would we rather look at GitHub Pages? 🤔

**Comment by derberg** [comment]
tbh @jonaslagoni  I didn't look into a single line of this sdk, so hard for me what are you generating, is it just API docs or some fancy react components playground 😄

**Comment by jonaslagoni** [comment]
It is basically just a glorified readme :D
billede

**Comment by derberg** [comment]
@jonaslagoni oh wow, this is fancy 😆 I think you can switch to the usual markdown docs as we have for generator and parser. Long term markdown will be even much easier to integrate with the website than this static HTML

btw, if you do not mention me in the comment, the toaster doesn't ping me

**Comment by jonaslagoni** [comment]
@derberg Alright I'll remove it :D

**Review by derberg — APPROVED** [review]

**Pull request merged**
